package:
  name: deepmei
  version: 1.6.24

source:
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/deepmei_update_v1.6.24.2.tar.gz
  sha256: 9a0fa0905776924969907cd71dfdf47e9e7afa8fc0ca277e30b2bf222efee3fd
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/candidate_locus.zip
  sha256: f2c86424f3d6c3d571115e107c24459b3d8f4759b4bac97447f5a1ca3fb2d394
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/batch_cdgc.zip
  sha256: f7f412eb39513997e908de9078f1c26246a89f1b46fc0a6a69b78edc91a1d3eb
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/keras_metadata.pb
  sha256: 1b97b4bb2aa55387a3a0743f5bac7a66b4dba15c1ad653fd265364d67937c250
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/saved_model.pb
  sha256: a851dcb8f9873762563fb0faf484fb75bc1558bf7ffa00187a75566f7bf69439
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.data-00000-of-00001aa
  sha256: 5ee4dffa81e8f356cf4d9bd244181996c59f757d6d9e3857c131dd7926af4907
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.data-00000-of-00001ab
  sha256: 363470d9b02136601b3301fffd5fdfff6e2ceaad553dfc060c99f08224ee6ca1
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.data-00000-of-00001ac
  sha256: 22086a61354169ba9e928a23c9dbf0ea4465d0b6a0ec8c2ca27058bb807e635b
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.data-00000-of-00001ad
  sha256: c9e583565f1881d25c01cc2e69a87983a9404b3ed571705edb0b1e81c50c19ec
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.data-00000-of-00001ae
  sha256: 9713cfc4d9650c501111a208a9d50a3b997873822ee9e25dfdb80ca2075574bb
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.data-00000-of-00001af
  sha256: fb241e56204a8353605c0f989b0a2e55df5ebac7b5fecadd27421e29aa710fa3
  url: https://github.com/xuxif/DeepMEI/raw/main/DeepMEI/DeepMEI_model/weights/val_best_model/variables/variables.index
  sha256: 1dafb6a02265afaba53ede6fa949d4ec71ea823a5e5c68d87ea0c335829f5b88
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/reference.00
  sha256: 6890027898851658d721c3da88f6def551fc5a30beea2474f1cd508e88030850
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/reference.01
  sha256: 8790e3aec17e53c032a76409dcf46805fc96a37229c3b8b9408987cd15d8731b
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/reference.02
  sha256: f99e6c437cc5aea582a77cfa9a0fb5b89e362956a2c68b4ac88433103ae59e16
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/reference.03
  sha256: d7f27b9a197aee13def0d106e4e23ac1e61b4fd169d5d33a1cf0714f89c7cefa
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/reference.04
  sha256: 74011677b5942e449f9175cdc705f4a4dfd9bf8472933b49a88af458af1dbbe3
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/reference.05
  sha256: 81ed3778a880b63f4a936b5a92a1a546888f291ba6c0f942a39c40491ca1d7e6
  
build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('deepmei', max_pin="x.x") }}
   
requirements:
  run:
    # List dependencies here. e.g.:
    # ... any other dependencies 
    - bedtools =2.30.0
    - bwa
    - pysam =0.17.0
    - repeatmasker
    - tensorflow =2.7.0
    - python >=3.8,<=3.9
    - perl =5.32.1
    - samtools
    
test:
  commands:
    - deepmei

about:
  home: https://github.com/Kanglu123/deepmei/tree/deepmei-v1.6.24
  license: GPL-3.0
  license_file: license.txt
  summary: A tool to detect mobile elements insertion
