package:
  name: deepmei
  version: 1.6.24

source:
  url: https://raw.githubusercontent.com/kanglu123/deepmei/deepmei-v1.6.24/deepmei_update_v1.6.24.2.tar.gz
  sha256: 91a4e1a7bf1f3e137ac84286b3e54726a4884980b4dda6cd0cefcfdcb31ea541
build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('deepmei', max_pin="x.x.x") }}
   
requirements:
  run:
    # List dependencies here. e.g.:
    # ... any other dependencies 
    - bedtools =2.30.0
    - bwa
    - pysam =0.17.0
    - repeatmasker
    - tensorflow =2.7.0
    - python >=3.8,<=3.9
    - perl =5.32.1
    - samtools
    
test:
  commands:
    - deepmei -h

about:
  home: https://github.com/Kanglu123/deepmei/tree/deepmei-v1.6.24
  license: GPL-3.0
  license_file: license.txt
  summary: A tool to detect mobile elements insertion
